# Generated by Django 3.2.6 on 2021-08-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_movie_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, null=True),
        ),
    ]
